# Azure App Service configuration
runtime: python
runtime_version: 3.13

# Environment variables
env_variables:
  PYTHONPATH: .
  MODEL_DIR: model
  API_KEY: your-secret-api-key
  ENVIRONMENT: production

# Startup command
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

# Scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10